project: 
  type: website
  
website: 
  page-navigation: true
  back-to-top-navigation: true
  title: AETR Web Book 
  site-url: "https://acep-uaf.github.io/aetr-web-book/" 
  repo-url: https://github.com/acep-uaf/aetr-web-book 
  other-links: 
    - href: mailto:uaf-acep-dcm-support@alaska.edu
      text: Report an issue via email
      icon: envelope-exclamation
  repo-actions: [issue]
 
  page-footer:
    right: "This page is based on Openscape's [Quarto Site Template](https://github.com/Openscapes/quarto-website-tutorial) and built with [Quarto](https://quarto.org/) ."
    left: "&copy; CC-By , 2023"
    
  sidebar:
    logo: "images/ACEP_gear.png"
    pinned: true
    align: center
    title: "<strong>2024 Alaska Electricity Trends Report</strong><br/><small><em>(Data Years 2011-2021)</em></small><br/>"
    tools: 
      - icon: globe
        href: https://www.uaf.edu/acep/
        text: "Alaska Center for Energy and Power"
      - icon: github
        href: https://github.com/acep-uaf/aetr-web-book
        text: "Project GitHub"      

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Summary
        icon: dot
      - href: about.qmd
        text: About this Report
        icon: dot
      - href: methods.qmd
        text: Methods
        icon: dot
      - href: capacity.qmd
        text: Capacity
        icon: dot
      - href: generation.qmd
        text: Net Generation
        icon: dot
      - href: consumption.qmd
        text: Consumption
        icon: dot
      - href: prices.qmd
        text: Price of Electricity
        icon: dot   
      - href: acronyms.qmd
        text: Definitions of Acronyms
        icon: dot
      - href: historic_reports.qmd
        text: Historical Reports
        icon: dot
      - href: data.qmd
        text: Data Portal
        icon: dot
      - href: credits.qmd
        text: About the Team
        icon: dot     

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      #dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true

date: last-modified
date-format: "MMM D, YYYY [at] HH:mm z"

filters:
  - quarto

  
